Header作成
KnK-n/cookids pull request #3
Opened 2023-09-07 13:06 UTC by KnK-n

Headerのレイアウト作成

2023-09-07 13:27 UTC, Naoto0213 requested changes

2023-09-07 13:27 UTC, Naoto0213 commented on src/app/components/button/button.tsx
> +  backgroundColor: "#FFD803",
よく使うコードはthemeを使用する

2023-09-07 13:27 UTC, Naoto0213 commented on src/app/components/header/header.tsx
> +  return (
const { user, error, isLoading } = useUser();
を使って内部で条件分岐する

2023-09-07 13:27 UTC, Naoto0213 commented on src/app/components/button/button.tsx
ファイル名はindex.tsx

2023-09-07 13:27 UTC, Naoto0213 commented on src/app/components/header/header.tsx
components/layout/header.tsx

2023-09-07 13:27 UTC, Naoto0213 commented on src/app/components/user.tsx
>    if (user) {
userではなく、isLoggedin的な物があればそちらを使う

2023-09-07 13:27 UTC, Naoto0213 commented on src/app/components/user.tsx
components/pages/user/index.tsx

2023-09-10 12:39 UTC, KnK-n commented on src/app/components/user.tsx
>    if (user) {
isLoggedinはuseUser()になかったので、userを使ってます。

2023-09-10 13:38 UTC, Naoto0213 requested changes
綺麗に書けてますね☺️
一点だけ！

2023-09-10 13:38 UTC, Naoto0213 commented on src/app/components/layout/header.tsx
> +        <div>
divタグを使用するのであれば、Boxタグを使用してしまって良いと思います👍

2023-09-10 13:38 UTC, Naoto0213 commented on src/app/components/layout/themeRegistry.tsx
完璧です🙌

2023-09-14 11:40 UTC, Naoto0213 commented
[![LGTMeow](https://lgtm-images.lgtmeow.com/2022/12/10/23/868f01be-bcfa-484b-8da1-a2ec6d4484e7.webp)](https://lgtmeow.com)

2023-09-14 11:40 UTC, merged